version: "3.9"
# compose file for nginx
services:
  nginx_main:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf" # <- configuration for nginx
  app1:
    image: amang385/nodejs-api:0.0.3
    restart: always
    ports:
      - "8081:3000"
  app2:
    image: amang385/nodejs-api:0.0.3
    restart: always
    ports:
      - "8082:3000"
  app3:
    image: amang385/nodejs-api:0.0.3
    restart: always
    ports:
      - "8083:3000"
  # webapp1:
  #   image: amang385/nodejs-api:0.0.3
  #   restart: always
  #   ports:
  #     - "8091:3000"
  # webapp2:
  #   image: amang385/nodejs-api:0.0.3
  #   restart: always
  #   ports:
  #     - "8092:3000"
